### ISSUE TITLE
Error with buildout

### ISSUE THREAD

**Issue by bigkrp** [collective/buildout.python#74]
When i run `./bin/buildout` i have an error

```
Getting distribution for 'buildout.extensionscripts'.
zip_safe flag not set; analyzing archive contents...
Got buildout.extensionscripts 1.0.
Getting distribution for 'plone.recipe.command'.
Got plone.recipe.command 1.1.
Getting distribution for 'hexagonit.recipe.download'.
Got hexagonit.recipe.download 1.7.1.
Getting distribution for 'collective.recipe.cmmi==0.5'.
Got collective.recipe.cmmi 0.5.
Getting distribution for 'zc.recipe.cmmi==1.3.5'.
Got zc.recipe.cmmi 1.3.5.
Getting distribution for 'collective.recipe.template==1.11'.
Got collective.recipe.template 1.11.
Getting distribution for 'z3c.recipe.runscript'.
Got z3c.recipe.runscript 0.1.3.
Unused options for buildout: 'python36-parts' 'python24-parts' 'python33-parts' 'pil-install-args' 'python26-parts' 'python32-parts' 'python34-parts' 'python37-parts' 'python35-parts' 'python25-parts'.
Updating opt.
opt: Running 
mkdir -p /data/work/buildouts/python/parts/opt && mkdir -p /data/work/buildouts/python/parts/opt/bin && mkdir -p /data/work/buildouts/python/parts/opt/man/man1
Updating virtualenv.
Updating readline.
Updating python-2.7-build.
Updating python-2.7-virtualenv.
Installing python-2.7.
python-2.7: Running '
/data/work/buildouts/python/parts/opt/bin/python2.7 /data/work/buildouts/python/src/ez_setup-latest.py
/data/work/buildouts/python/parts/opt/bin/easy_install-2.7 -U pip
/data/work/buildouts/python/bin/virtualenv-2.7 --system-site-packages /data/work/buildouts/python/python-2.7'
ez_setup.py is deprecated and when using it setuptools will be pinned to 33.1.1 since it's the last version that supports setuptools self upgrade/installation, check https://github.com/pypa/setuptools/issues/581 for more info; use pip to install setuptools
Extracting in /tmp/tmpk5DMkf
Now working in /tmp/tmpk5DMkf/setuptools-33.1.1
Installing Setuptools
Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    import setuptools
  File "/tmp/tmpk5DMkf/setuptools-33.1.1/setuptools/__init__.py", line 10, in <module>
    from setuptools.extern.six.moves import filter, map
  File "/tmp/tmpk5DMkf/setuptools-33.1.1/setuptools/extern/__init__.py", line 1, in <module>
    from pkg_resources.extern import VendorImporter
ImportError: No module named extern
Something went wrong during the installation.
See the error message above.
/bin/sh: строка 2: /data/work/buildouts/python/parts/opt/bin/easy_install-2.7: No such file or directory
Traceback (most recent call last):
  File "/data/work/buildouts/python/parts/virtualenv/virtualenv.py", line 2332, in <module>
    main()
  File "/data/work/buildouts/python/parts/virtualenv/virtualenv.py", line 711, in main
    symlink=options.symlink)
  File "/data/work/buildouts/python/parts/virtualenv/virtualenv.py", line 924, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/data/work/buildouts/python/parts/virtualenv/virtualenv.py", line 1144, in install_python
    site_filename_dst = change_prefix(site_filename, home_dir)
  File "/data/work/buildouts/python/parts/virtualenv/virtualenv.py", line 1035, in change_prefix
    (filename, prefixes)
AssertionError: Filename /data/work/buildouts/python/parts/buildout/site.py does not start with any of these prefixes: ['/data/work/buildouts/python/parts/opt']
python-2.7: Non zero exit code (1) while running command.
While:
  Installing python-2.7.
Error: Non zero exit code (1) while running command.
```

**Comment by mjpieters** [comment]
Resolved with ed40acef2f429afdbe9cc60d79d62327a5a9f583
